USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOTBALL_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS FOOTBALL_DB.RAW.RAW_FIXTURES (
    raw_data    VARIANT,
    loaded_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FOOTBALL_DB.RAW.RAW_STANDINGS (
    raw_data    VARIANT,
    loaded_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FOOTBALL_DB.RAW.RAW_PLAYERS (
    raw_data    VARIANT,
    loaded_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO FOOTBALL_DB.RAW.RAW_FIXTURES (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/matches/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_STANDINGS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/standings/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_PLAYERS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/players/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

SELECT 'fixtures' AS table_name, COUNT(*) AS nb FROM FOOTBALL_DB.RAW.RAW_FIXTURES
UNION ALL
SELECT 'standings', COUNT(*) FROM FOOTBALL_DB.RAW.RAW_STANDINGS
UNION ALL
SELECT 'players', COUNT(*) FROM FOOTBALL_DB.RAW.RAW_PLAYERS;

SELECT raw_data:results::INTEGER AS nb_fixtures,
       raw_data:parameters:league::INTEGER AS league_id
FROM FOOTBALL_DB.RAW.RAW_FIXTURES;