-- Run this script to reload data from GCS into Snowflake
-- Use after a fresh ingestion run

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOTBALL_DB;
USE SCHEMA RAW;

-- Clear existing data
TRUNCATE TABLE RAW_FIXTURES;
TRUNCATE TABLE RAW_STANDINGS;
TRUNCATE TABLE RAW_PLAYERS;

-- Reload from GCS stage
COPY INTO FOOTBALL_DB.RAW.RAW_FIXTURES (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/matches/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_STANDINGS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/standings/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_PLAYERS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/players/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

-- Verify
SELECT 'fixtures' AS table_name, COUNT(*) AS nb FROM FOOTBALL_DB.RAW.RAW_FIXTURES
UNION ALL
SELECT 'standings', COUNT(*) FROM FOOTBALL_DB.RAW.RAW_STANDINGS
UNION ALL
SELECT 'players', COUNT(*) FROM FOOTBALL_DB.RAW.RAW_PLAYERS;