-- Run this script to reload data from GCS into Snowflake
-- Use after a fresh ingestion run

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOTBALL_DB;
USE SCHEMA RAW;

-- Drop and recreate tables to purge load history
DROP TABLE IF EXISTS RAW_FIXTURES;
DROP TABLE IF EXISTS RAW_STANDINGS;
DROP TABLE IF EXISTS RAW_PLAYERS;

CREATE TABLE RAW_FIXTURES (raw_data VARIANT, loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE RAW_STANDINGS (raw_data VARIANT, loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE RAW_PLAYERS (raw_data VARIANT, loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP());

-- Reload from GCS (skips .keep files by pointing to year folder)
COPY INTO FOOTBALL_DB.RAW.RAW_FIXTURES (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/matches/2026/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_STANDINGS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/standings/2026/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

COPY INTO FOOTBALL_DB.RAW.RAW_PLAYERS (raw_data)
FROM (SELECT $1 FROM @FOOTBALL_DB.RAW.GCS_STAGE/players/2026/)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'CONTINUE';

-- Verify
SELECT raw_data:parameters:league::INTEGER AS league_id,
       raw_data:results::INTEGER AS nb_results
FROM FOOTBALL_DB.RAW.RAW_FIXTURES;